query allProducts($first: Int = 50) {
  products(first: $first) {
    nodes {
      id
      handle
      title
      tags
      productType
      priceRange {
        minVariantPrice {
          amount
        }
      }
      images(first: 5) {
        nodes {
          url
        }
      }
      collections(first: 2) {
        nodes {
          title
        }
      }
    }
  }
}

query allProductsInCategory($collection: ID, $first: Int = 50) {
  collection(id: $collection) {
    handle
    products(first: $first) {
      nodes {
        id
        handle
        title
        tags
        productType
        priceRange {
          minVariantPrice {
            amount
          }
        }
        images(first: 5) {
          nodes {
            url
          }
        }
        collections(first: 2) {
          nodes {
            title
          }
        }
      }
    }
  }
}

query singleProduct($product: ID) {
  product(id: $product) {
    title
    handle
    tags
    productType
    descriptionHtml
    priceRange {
      minVariantPrice {
        amount
      }
    }
    images(first: 5) {
      nodes {
        url
      }
    }
    collections(first: 2) {
      nodes {
        title
      }
    }
  }
}
